apiVersion: v1
kind: Pod
metadata:
  name: wordpress-nginx
  namespace: wordpress
  labels:
    app: wordpress-nginx
spec:
  containers:
    - name: wordpress
      image: wordpress:php8.2-fpm
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
      volumeMounts:
        - name: www
          mountPath: /var/www/html

    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: www
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d

    - name: nginx-exporter
      image: nginx/nginx-prometheus-exporter:latest
      args:
        - "-nginx.scrape-uri=http://localhost/nginx_status"
      ports:
        - containerPort: 9113

  volumes:
    - name: www
      emptyDir: {}
    - name: nginx-config
      configMap:
        name: nginx-config
